//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capgemini.Pecunia.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeLoan
    {
        public System.Guid LoanID { get; set; }
        public Nullable<System.Guid> CustomerID { get; set; }
        public Nullable<decimal> AmountApplied { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public Nullable<decimal> EMI_amount { get; set; }
        public Nullable<byte> RepaymentPeriod { get; set; }
        public Nullable<System.DateTime> DateOfApplication { get; set; }
        public string LoanStatus { get; set; }
        public string Occupation { get; set; }
        public Nullable<byte> ServiceYears { get; set; }
        public Nullable<decimal> GrossIncome { get; set; }
        public Nullable<decimal> SalaryDeduction { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
